### ISSUE TITLE
Query params not escaped in url, resulting in invalid curl command.

### ISSUE THREAD

**Issue by m-abs** [amingolmahalle/HttpClientToCurlGenerator#13]
Hi,

Thanks for the plugin, it was a great for debugging.

Minor problem, query params are not escaped.

Example:
```c#
var queryArgs = new Dictionary<string, StringValues>
{  
     { "memberId", "Morten Sjøgren" },
};

var uri = new Uri(QueryHelpers.AddQueryString("http://internal-backend.lan/rest/path", queryArgs));
```

I'd expect this to become:

```bash
curl http://internal-system.lan/rest/path\?memberName=Morten%20Sj%C3%B8gren
```

But I get this:

```bash
curl http://internal-system.lan/rest/path\?memberName=Morten Sjøgren
```

Which of course doesn't work because of the space and the unescaped danish letter `ø`.

**Comment by amingolmahalle** [comment]
Hello dear Morten. I'm happy this extension was useful for you. I'm sorry about this issue. I sure check this problem and I will fix it.
Thank you.
