### ISSUE TITLE
Quote the URL

### ISSUE THREAD

**Issue by kokoabim** [amingolmahalle/HttpClientToCurlGenerator#23]
On the outputted cURL command-line, add quotes around the URL to prevent characters like `?` and `&` being handled by a shell.

Example: Instead of `curl https://foo.com?bar=baz&red=sox`, change it to be `curl 'https://foo.com?bar=baz&red=sox'`

Without quoting, every command-line with characters like these must be edited prior to execution.

**Comment by amingolmahalle** [comment]
Thank you dear @kokoabim
I agree with you.

**Comment by Sabermotamedi** [comment]
I will make this changes, assign it to me
