### ISSUE TITLE
Show more details in case of errors

### ISSUE THREAD

**Issue by Sabermotamedi** [amingolmahalle/HttpClientToCurlGenerator#3]
I tried to find my error by your extension but I  only received this message: 
"GenerateCurlError => Object reference not set to an instance of an object..".

Definitely, this message is not enough for me to find my fault it's better to be aware of which object is null or has a problem.

I will fix it.

**Comment by amingolmahalle** [comment]
Yes, You're right. it's better to show more detail about an error in the message. thanks to the issue.

**Comment by Sabermotamedi** [comment]
Thanks for your merge
sure, I will show more detail
