### ISSUE TITLE
add pre-commit and pre-push files to curl generator 

### ISSUE THREAD

**Issue by Sabermotamedi** [amingolmahalle/HttpClientToCurlGenerator#30]
**Description:**

We need to add pre-commit and pre-push hooks to enhance awareness of our code quality.

**Steps to Reproduce:**

To achieve this, we should add a configuration file to the project.

**Expected Behavior:**

Contributors will be more confident about their code quality as it will be automatically checked before commits and pushes.

**Additional Information:**

An additional file is suggested to be added to the project to implement these hooks.

Please review and consider implementing this enhancement.

[pre-commit.zip](https://github.com/amingolmahalle/HttpClientToCurlGenerator/files/13955011/pre-commit.zip)

**Comment by Sabermotamedi** [comment]
assign it to me, I will do it.

**Comment by amingolmahalle** [comment]
closed
