### ISSUE TITLE
There are differences in generating cURLs

### ISSUE THREAD

**Issue by wf-soft** [amingolmahalle/HttpClientToCurlGenerator#45]
1. The generated string has multiple URL encodings (%3D->%253D)
2. The Headers value after production exists ";" Number, etc., causing inconsistency in the original User Agent
In some application scenarios, it is necessary to ensure that the parameters are highly consistent and no differences are allowed, otherwise the request will fail

**Comment by amingolmahalle** [comment]
Hello, dear @wf-soft.thank you for your attention.
please send us a more description along with sample codes for your steps for better understanding of your issues and fixing them.
also if you like I can assign this issue to you.
