### ISSUE TITLE
Add the issue sample template

### ISSUE THREAD

**Issue by amingolmahalle** [amingolmahalle/HttpClientToCurlGenerator#46]
This allows contributors to use a predefined template when creating new issues, ensuring consistent and useful bug reports or feature requests.

**Comment by amingolmahalle** [comment]
For Example:

# Issue Report

## Description
Provide a clear and concise description of the issue you are experiencing.

## Steps to Reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected Behavior
Describe what you expected to happen.

## Actual Behavior
Describe the actual behavior you observed.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Environment
 - IDE: [e.g. Rider, Vs Code, Visual Studio]
 - OS: [e.g. Windows 11, Ubuntu 22.04, Debian 11 ]
 - DOTNET_VERSION: [e.g. 3.0, 5.0, 8.0]
 - NUGET_VERSION: [e.g. 2.0.6]

## Additional Context
Add any other context about the problem here.

**Comment by Shahinmm69** [comment]
Please assign me the issue
