### ISSUE TITLE
Why BaseUrl of HttpClient is mandatory?

### ISSUE THREAD

**Issue by naeemaei** [amingolmahalle/HttpClientToCurlGenerator#9]
In some scenarios, I want to set an absolute path in `HttpRequestMessage` but had forced me to use `HttpClient` BaseUrl.
It would be great if there was a way I could just set the absolute path in the `HttpRequestMessage`.

**Comment by amingolmahalle** [comment]
Yes, you're right. I will fix this problem soon.
